# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: DOCS=1
    - python: 3.4
    - python: 3.5
    - python: 3.6
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libsuitesparse-dev
    - gfortran
    - swig
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - set -o pipefail
  - travis_retry pip install --upgrade pip wheel   # get pip >= 7, which caches built packages
  - travis_retry pip install numpy
  # Convert pip output to dots so that Travis doesn't quit while scipy is building
  - (pip install -v scipy 2>&1 | tee scipy-build.log | perl -e 'my $start=time(); local $|=1; while (<STDIN>) { if (time() > $start + 5) { print "."; $start=time(); }; }') || { cat scipy-build.log; exit 1; }
  - |
    if [ "$DOCS" == "1" ]; then
        travis_retry pip install Sphinx numpydoc
    fi
script:
  - python setup.py test
  - |
    if [ "$DOCS" == "1" ]; then
        python setup.py build_sphinx
    fi
notifications:
  email: false
